version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-api
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser -d apidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  jboss-api:
    build: .
    container_name: jboss-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=apidb
      - DB_USER=apiuser
      - DB_PASS=apipass

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge

